default_language_version:
    python: python3.9

repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
        description: "Attempts to load all yaml files to verify syntax"
        args: ['--unsafe']
    -   id: end-of-file-fixer
        description: "Makes sure files end in a newline and only a newline"
    -   id: trailing-whitespace
        description: "Trims trailing whitespace"
        language_version: python3
    -   id: check-added-large-files
        description: "Prevent giant files from being committed"
        args: ['--maxkb=8000']
    -   id: debug-statements
        description: "Check for debugger imports and breakpoint() calls in python source"
    -   id: name-tests-test
        description: "Verifies that test files are named correctly"
        args: ['--pytest-test-first']
        exclude: ^pinax/blog/tests/urls.py
    -   id: pretty-format-json
        description: "Checks that all your JSON files are are sorted and indented"
        args: ['--autofix', '--indent=2']
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        description: "Sort imports alphabetically and separated into sections and by type"
        args: ["--profile", "black", "--filter-files"]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.4.0
    hooks:
    -   id: pyupgrade
        description: "Automatically upgrade syntax for newer versions of the language"
-   repo: 'https://github.com/psf/black'
    rev: 23.3.0
    hooks:
      - id: black
        description: "Black is the uncompromising Python code formatter"
-   repo: https://github.com/awslabs/cfn-python-lint
    rev: v0.77.6
    hooks:
    -   id: cfn-python-lint
        files: cloudformation/.*\.(yml|yaml)$
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    -   id: bandit
        description: "Bandit is a tool for finding common security issues in Python code"
        args: ["-c", "bandit.yml"]
